apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <Manifest-Repo-URL> # Change this to your manifest repository URL
    targetRevision: HEAD
    path: task-app  
  destination:
    server: https://kubernetes.default.svc
    namespace: task-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <Manifest-Repo-URL> # Change this to your manifest repository URL
    targetRevision: HEAD
    path: datadog
  destination:
    server: https://kubernetes.default.svc
    namespace: datadog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true